### ISSUE TITLE
如何让GLTextureView背景透明？

### ISSUE THREAD

**Issue by jeaman** [ChillingVan/android-openGL-canvas#1]
背景是黑色，如何让它透明，看了代码，mCanvas.clearBuffer(Color.TRANSPARENT);无效，还是黑色背景

**Comment by ChillingVan** [comment]
可以使用 TextureView 的 setOpaque(false) 实现透明。

**Comment by jeaman** [comment]
已经找到该解决方法了，非常感谢，这个glTextureView解决了我的大问题

**Comment by ChillingVan** [comment]
哈哈，那就好

**Comment by yjbGitHub** [comment]
> 已经找到该解决方法了，非常感谢，这个glTextureView解决了我的大问题

大神，你是如何解决textureview背景透明的？

**Comment by crazy1235** [comment]
同问 如何设置textureview背景透明的？ @jeaman @yjbGitHub

**Comment by ChillingVan** [comment]
@crazy1235  可以用setOpaque

**Comment by crazy1235** [comment]
> @crazy1235 可以用setOpaque

这个不好用。设置了还是不透明

**Comment by ChillingVan** [comment]
> 
> 
> > @crazy1235 可以用setOpaque
> 
> 这个不好用。设置了还是不透明

能截图看看吗？
我这是可以的：
![图片](https://user-images.githubusercontent.com/7666419/59975255-f5c83200-95e8-11e9-95c8-b8c266b5ecca.png)
