### ISSUE TITLE
如何复用Bitmap， 显示大量连续的帧图片

### ISSUE THREAD

**Issue by ml-bright** [ChillingVan/android-openGL-canvas#10]
#2 在这里我看到一张解决方案：
if (bitmapTextureMap.containsKey(bitmap)) {
resultTexture = bitmapTextureMap.get(bitmap);
} else {
resultTexture = new BitmapTexture(bitmap);
bitmapTextureMap.put(bitmap, resultTexture);
}
改为
resultTexture = new BitmapTexture(bitmap);
bitmapTextureMap.put(bitmap, resultTexture);

这样虽然能达到效果，但是作者也说了，不断新增 texture 而不清理掉旧的，很快就会资源不足而崩溃的

还有一种是每次修改BitmapTexture里面的bitmap，然后调用invalidateContent，这样也能达到效果，
但是还是会内存不足挂掉，请问下还有别的方法可以实现吗

**Comment by ml-bright** [comment]
为了性能，我的bitmap也是同一个，通过Bitmap.Option.inBitmap属性复用bitmap内存空间的，所以才会有这些问题

**Comment by ChillingVan** [comment]
所以你的需求其实是修改同一个bitmap，然后不断地将它显示对吧？

**Comment by ChillingVan** [comment]
就是说需要加载大量PNG图片，并由此组成动画？如果这样的话，建议每秒读取一部分，在显示的同时在另一个线程里先把下一部分加载出来，把已经显示过的清理掉。

**Comment by ChillingVan** [comment]
挺好奇为什么会用大量连续的图片显示动画效果，这样的形式无论如何也不算性能友好，不能以例如视频的形式播放吗？

**Comment by ml-bright** [comment]
是的，可用用视频播放，我现在做的是一个视频编辑器，需要显示三层视频效果，第一层背景层是一个视频，中间层是用bitmap做的一些动画效果，最上层的也可以是一个视频，也可以是由许多图片连续播放。GLTextureView可以实现这样的效果吗

**Comment by ml-bright** [comment]
“就是说需要加载大量PNG图片，并由此组成动画？如果这样的话，建议每秒读取一部分，在显示的同时在另一个线程里先把下一部分加载出来，把已经显示过的清理掉。”

这些操作都做了，bitmap解码这块已经没问题了，问题在于显示，把bitmap画到ICanvasGL上，会遇到内存溢出的问题

**Comment by ChillingVan** [comment]
这个效果是可以实现的，本质上就是 
第一层绘制视频帧
第二层绘制图片
第三层绘制另一视频帧

**Comment by ChillingVan** [comment]
图片的清晰度可以降低吗？还有你确认之前绘制的需要清理bitmap的引用设为Null了吗？
因为bitmapTextureMap是WeakHashMap，如果其它地方有强引用的话，它是不会清除的。

**Comment by ml-bright** [comment]
1. 目前在测试阶段先测试，没有图片的清晰度
2. 我稍微修改了下：
BasicTexture resultTexture;
        if (bitmapTextureMap.containsKey(bitmap)) {
            resultTexture = bitmapTextureMap.get(bitmap);
        } else {
            resultTexture = new BitmapTexture(bitmap);
            bitmapTextureMap.put(bitmap, resultTexture);
        }
改为：BitmapTexture resultTexture = new BitmapTexture(bitmap)；
然后把 resultTexture作为全局变量，每次更新的时候，修改下bitmapTexture里面的bitmap,然后调用invalidateContent()

这样做会存在问题吗?

**Comment by ml-bright** [comment]
“这个效果是可以实现的，本质上就是
第一层绘制视频帧
第二层绘制图片
第三层绘制另一视频帧“

关于这个，可以在同一个view中渲染吗，如何实现，是否需要继承GlVideoSharedView来共享来自其他View的视频？

**Comment by ml-bright** [comment]
把BitmapTexture 作为全局变量，每次更新的时候修改下里面的bitmap，然后调用invalidateContent()方法，就不会有可以实现我想要的效果了，而且不会出现内存溢出了，哈哈，太感谢作者了，非常好的一个库

**Comment by ChillingVan** [comment]
> “这个效果是可以实现的，本质上就是
> 第一层绘制视频帧
> 第二层绘制图片
> 第三层绘制另一视频帧“
> 
> 关于这个，可以在同一个view中渲染吗，如何实现，是否需要继承GlVideoSharedView来共享来自其他View的视频？

可以参考例子里的TextureCamera的实现。本质MediaCodec解码时可以输出到一个Surface里，Surface可以new Surface(SurfaceTexture)来创建。而GLSurfaceTextureProducerView既可以向外提供SurfaceTexture，也就是向解码的MedieCodec提供，也可以接收外部的SurfaceTexture，这样就可以绘制不同地方来的Texture到同一个View。

**Comment by ChillingVan** [comment]
不用谢，你最好多测试...可以在Android Studio里看看内存消耗

**Comment by ml-bright** [comment]
已解决

**Comment by ChillingVan** [comment]
最新版我添加了新的API invalidateTextureContent(Bitmap bitmap) 到 CanvasGL，你可以试试。

**Comment by ml-bright** [comment]
好的，已经知道如何在`GLSurfaceTextureProducerView`中显示多层视频啦，这个库很棒。赞一个
关键代码：
```
    private SurfaceTexture producedSurfaceTexture;
    private RawTexture producedRawTexture;
```
改为
```
    private SurfaceTexture[] producedSurfaceTextures;
    private RawTexture[] producedRawTextures;

    @Override
    public void onSurfaceChanged(int width, int height) {
        super.onSurfaceChanged(width, height);
        producedRawTextures = producedRawTextures == null ? new RawTexture[VIDEO_SIZE] : producedRawTextures;
        producedSurfaceTextures = producedSurfaceTextures == null ? new SurfaceTexture[VIDEO_SIZE] : producedSurfaceTextures;
        for (int i=0; i<producedSurfaceTextures.length; i++) {
            if (producedRawTextures[i] == null) {
                producedRawTextures[i] = new RawTexture(width, height, false, producedTextureTarget);
                if (!producedRawTextures[i].isLoaded()) {
                    producedRawTextures[i].prepare(mCanvas.getGlCanvas());
                }
                producedSurfaceTextures[i] = new SurfaceTexture(producedRawTextures[i].getId());
                if(i == producedSurfaceTextures.length - 1) {
                    post(new Runnable() {
                        @Override
                        public void run() {
                            if (onSurfaceTextureSet != null) {
                                onSurfaceTextureSet.onSet(producedSurfaceTextures, producedRawTextures);
                            }
                        }
                    });
                }
            } else {
                producedRawTextures[i].setSize(width, height);
            }
        }
    }

```
同时相应的地方都改成数组的形式即可
