### ISSUE TITLE
请问绘制的水印如何和视频流合并，一起推送到服务器？

### ISSUE THREAD

**Issue by ulongx** [ChillingVan/android-openGL-canvas#108]
我发现推流端屏幕上有“白色, White”字样，但是到了观看端显示的视频就没有了，请问如何一起推过去呢？

**Comment by ChillingVan** [comment]
例子里少写了一行，已经修复了。
https://github.com/ChillingVan/AndroidInstantVideo/commit/1e7cad6dab041814e30b1122f2235bd1811f80ae
```java
canvasGL.drawBitmap(outputBitmap, 0, 0);
```

**Comment by ulongx** [comment]
嗯嗯，感谢回答，我看到的 TestCameraPublisherActivity 里面的，在 类 CameraPreviewTextureView的onGLDraw里是有写的
```
canvasGL.drawBitmap(outputBitmap, 0, 0);
```
<img width="616" alt="image" src="https://user-images.githubusercontent.com/1161624/201567303-0be5aea9-aedf-4b7f-9627-96e83f9ceb7e.png">

屏幕上也能正常显示水印，但是推流到服务器上的，水印就没有了。
* 推送端
* 
![image](https://user-images.githubusercontent.com/1161624/201567129-e3511502-f64a-4fa2-90bc-85b6cd638cce.png)

* 小程序观看端
* 
![image](https://user-images.githubusercontent.com/1161624/201567165-5c1e7e3c-ae9b-4ff4-993d-efe9e1476c66.png)

**Comment by ulongx** [comment]
我知道怎么弄了～:) 谢谢
