### ISSUE TITLE
Crash when bringing app back to front?

### ISSUE THREAD

**Issue by jianhui1012** [ChillingVan/android-openGL-canvas#12]
I replaced GLSurfaceView with  the BaseGLTextureView,but I've got an issue on API 23 (6.0), when I press the home button to return to main screen and call my app again (restored). Then compare the GLSurfaceView code, I found the question of renew GLThread,I try comment the onSurfaceTextureDestroyed Method below code, not will crash. appear another question,preview the camera will delay and the fps of play video  also becomes low.
> mGLThread.requestRenderAndWait();
    mGLThread = null;

Thank for you help
```
java.lang.RuntimeException: glGetError encountered (see log)
                                                                                 at com.laifeng.sopcastsdk.video.GlUtil.checkGlError(GlUtil.java:110)
                                                                                 at com.laifeng.sopcastsdk.video.effect.Effect.draw(Effect.java:203)
                                                                                 at com.laifeng.sopcastsdk.video.GLMyViewRenderer.onDrawFrame(GLMyViewRenderer.java:139)
                                                                                 at com.chillingvan.canvasgl.glview.texture.gles.GLThread.guardedRun(GLThread.java:406)
                                                                                 at com.chillingvan.canvasgl.glview.texture.gles.GLThread.run(GLThread.java:133)
```

**Comment by ChillingVan** [comment]
I cannot reproduce it. Which sample do you use? TextureCameraActivity?

**Comment by jianhui1012** [comment]
I don't use the smaple example ，I modfity  the code in the [SopCastComponent](https://github.com/LaiFeng-Android/SopCastComponent) project.
>from  RenderSurfaceView extends GLSurfaceView to  extends GLTextureView

After, I try use the TestCameraPublisherActivity of [AndroidInstantVideo](https://github.com/ChillingVan/AndroidInstantVideo), replace with my rtmp address  in the startPublish method, but it looks publish fail , no video in the player and canot continue test .

**Comment by jianhui1012** [comment]
there is my modifty project:[SopCastComponent](https://github.com/jianhui1012/SopCastComponent).

**Comment by ChillingVan** [comment]
@jianhui1012 For the rtmp, try to start your player first, then start the server and publish your video.

**Comment by ChillingVan** [comment]
And you cannot simply replace GLSurfaceView with GLTextureView...Please see my samples about how to use GLTextureView.

**Comment by jianhui1012** [comment]
Thank for your reply , I'll try it.

**Comment by jianhui1012** [comment]
I'll try the TestCameraPublisherActivity of [AndroidInstantVideo](https://github.com/ChillingVan/AndroidInstantVideo) , found bringing app front to  back will stop Publish because GLThread would been destoryed. if i want to continue publish how can i do this?

**Comment by jianhui1012** [comment]
i solve this problem,when bringing app front to back,init render and publishcontroller. Thank you for help again.

**Comment by ChillingVan** [comment]
.... So 

> if i want to continue publish how can i do this?

You complete this?
@jianhui1012

**Comment by jianhui1012** [comment]
Yes.. I change the another method,when called surfaceDestoryed  ,by doing  init setRender,publishcontroller, i also achieve the desired effect.  
> using your  BaseGLTextureView and modfity the code in the SopCastComponent project.

Otherwise,i found that the post(new Runnable) of code would block when i save the disk by the Bitmap  object in the  the getDrawingBitmap method . Found callback ui thread, i modifty the way of start a new thread.

```
public void getDrawingBitmap(final Rect rect, final GLView.GetDrawingCacheCallback getDrawingCacheCallback) {
        queueEvent(new Runnable() {
            @Override
            public void run() {
                onDrawFrame();
                onDrawFrame();
                final Bitmap bitmapFromGLSurface = OpenGLUtil.createBitmapFromGLSurface(rect.left, rect.top, rect.right - rect.left, rect.bottom - rect.top, getHeight());

                post(new Runnable() {
                    @Override
                    public void run() {
                        getDrawingCacheCallback.onFetch(bitmapFromGLSurface);
                    }
                });
            }
        });
        requestRender();
    }```
