### ISSUE TITLE
摄像头预览界面是镜像的。

### ISSUE THREAD

**Issue by SuperShameless** [ChillingVan/android-openGL-canvas#18]
Demo 的TextureCamera 显示图像是镜像的，是否纹理贴图坐标不对？

**Comment by ChillingVan** [comment]
应该是前置摄像头的拍摄导致的，你可以对比一下你的相机应用

**Comment by SuperShameless** [comment]
GLSurfaceTextureProducerView 摄像头预览画面是Vertical镜像的，fork了份代码，修改如下：
https://github.com/SuperShameless/android-openGL-canvas/commit/cca53a1739069f61816ae3b275c4f799465807d6

**Comment by ChillingVan** [comment]
我的意思是前置摄像头本身捕获的画面就是这样的，不必在这里改。如果用到这个库需要调整时，就自行调整，不必修改库代码。

**Comment by SuperShameless** [comment]
明白了，感谢！
