### ISSUE TITLE
Bitmap如何复用

### ISSUE THREAD

**Issue by AipingLei** [ChillingVan/android-openGL-canvas#2]
if (bitmapTextureMap.containsKey(bitmap)) {
            resultTexture = bitmapTextureMap.get(bitmap);
        } else {
            resultTexture = new BitmapTexture(bitmap);
            bitmapTextureMap.put(bitmap, resultTexture);
 }
这个地方以Bitmap的引用作为key，想问下，为了性能，我的bitmap是同一个，而每次我都通过Canvas动态更新Bitmap，但返回的纹理视图永远是第一个创建的，请问有没有办法动态更新Bitmap所对应的纹理

**Comment by AipingLei** [comment]
我自己做了一个修改 
if (bitmapTextureMap.containsKey(bitmap)) {
resultTexture = bitmapTextureMap.get(bitmap);
} else {
resultTexture = new BitmapTexture(bitmap);
bitmapTextureMap.put(bitmap, resultTexture);
}
改为
  resultTexture = new BitmapTexture(bitmap);
    bitmapTextureMap.put(bitmap, resultTexture);
每次创建一个新的纹理BitmapTexture对象，可以达到这个效果。但还是想知道Bitmap更新了之后，是否可以不创建新纹理，而有没有一个类似update的方法来更新当前所对应的问题。不知道我描述清楚没，我的需求其实就是要在一张位图上面画轨迹，然后把这个位图纹理合并到视频帧所对应的纹理中

**Comment by ChillingVan** [comment]
你的意思相当于是合并多张图片吧？如果合并后的输出是以 Bitmap 的形式的话，那就用 getDrawingBitmap 方法，注意这个方法比较耗性能。
如果合并后是以 Texture 的方式输出，那么直接输出 Texture 的 id 就行， 每个 Texture 都有一个 int 类型的 id，这个id在同一个 GLContext 里面是通用的。具体可以参考例子里的 GLSurfaceTextureProducerView 和 GLSharedContextView 的用法。应该不需要改代码的。

**Comment by ChillingVan** [comment]
另外你改的代码里，不断新增 texture 而不清理掉旧的，很快就会资源不足而崩溃的

**Comment by AipingLei** [comment]
恩，我只是一种尝试，具体不会向上面这样做的。我的需求通过调用了下面这个方法，每次不用重新创建纹理，实际上是每次执行了一次texSubImage2D操作
protected void invalidateContent() {
        if (mBitmap != null) freeBitmap();
        mContentValid = false;
        mWidth = UNSPECIFIED;
        mHeight = UNSPECIFIED;
    }

**Comment by ChillingVan** [comment]
我不知道你的代码具体是怎样的，但是感觉好像你把给 BitmapTexture 的 bitmap 对象里面的内容改掉了。我之前说的都是不改变 bitmap 本身内容的。
反正解决了就好，个人觉得应该也可以。

**Comment by AipingLei** [comment]
对，我就是把bitmap本身的内容改掉了。感觉效率还OK，后期观察一下吧，我现在主要就是做个视频编辑器，视频录制的同时在画面上加一些动画，动态轨迹，浮标什么的，用OPENGL感觉比较繁琐，还有在你这边找到了一个封装库，多谢了！
