### ISSUE TITLE
请问 Matrix  要怎么样才能绕着bitmap中心旋转  

### ISSUE THREAD

**Issue by zhouwenhao** [ChillingVan/android-openGL-canvas#20]

**Comment by ChillingVan** [comment]
是指ICanvasGL里的BitmapMatrix吗？默认就是围绕中心的。

**Comment by zhouwenhao** [comment]
是的   matrix.rotateZ(rotation);
        matrix.scale(sx, sy);      没有平移     bitmap并非围绕中心

**Comment by zhouwenhao** [comment]
matrix.rotateZ(rotation);
        matrix.scale(sx, sy);
        matrix.translate(rect.left, rect.top);

rect是缩放后的bitmap的rect，想要图片居正中，   可是一直无法实现   求救  用的ICanvasGL里的BitmapMatrix

**Comment by zhouwenhao** [comment]
图片居于屏幕正中

**Comment by ChillingVan** [comment]
`        CanvasGL.BitmapMatrix matrix = new CanvasGL.BitmapMatrix();
//        matrix.scale(1.3f, 1.3f);
        matrix.translate(360, 180);
        canvas.drawBitmap(baboon, matrix);`

CompareGLView.java里，你改成这样试试，matrix.scale(1.3f, 1.3f);这句有无不影响左上角

**Comment by zhouwenhao** [comment]
没有画弧线的API吗

**Comment by ChillingVan** [comment]
没有，如果弧线不多的话，可以先把弧线画到Bitmap上，再画Bitmap就可以了

**Comment by zhouwenhao** [comment]
如何使用官方canvas的叠加模式呢

**Comment by ChillingVan** [comment]
不知叠加模式指的是什么。可能LightenBlendFilter或者DarkenBlendFilter可以。
