### ISSUE TITLE
几个OffscreenCanvas的问题

### ISSUE THREAD

**Issue by FangGet** [ChillingVan/android-openGL-canvas#24]
感谢开源该项目，当前刚好能用到，这几有几个小问题，不知道您能否帮忙解答下：
1. 我现在有一个SurfaceTexture得到的textureid，如何从该id中高效的取出图像数据？
2.我看OffscreenCanvas封装了不同的texture，如果我只想利用1中的id来进行绘制，该怎么解决？

**Comment by ChillingVan** [comment]
1. 图像数据是指Bitmap吗？可以获取Bitmap，但不怎么高效。用getDrawingBitmap方法可以获取
2. OffScreenCanvas里不同的texture不同用途。可以参考GLSurfaceTextureProducerView的例子
