### ISSUE TITLE
Surfaceview里面的独立线程绘图。

### ISSUE THREAD

**Issue by submarinexu** [ChillingVan/android-openGL-canvas#25]
你好,向您提个问题。我现在的APP里面使用安卓自带surfaceview里面的canvas来进行点阵绘图。但是模拟器测量下来，整个绘图过程耗时将近60mS。达不到每秒钟24帧的最低刷新率。查询了一下，surfaceview里面的canvas绘图是没有GPU参与加速的，导致了绘图耗时过大。
网上搜到您写的这个类库，特向您请教，如果使用您这个类库的话是否能实现GPU参与加速的Canvas绘图？
您的类库里面哪个模块比较和我现在使用的canvas接近？
谢谢！

**Comment by ChillingVan** [comment]
我的库能做到。但是我的库绘制文字性能不会有多大提高。你的问题，只要把SurfaceView换成View就可以解决了。我的在README里提到的博客有关于你这种问题的详细解答。

**Comment by submarinexu** [comment]
谢谢您的回答。我是需要一个独立的线程在主界面上绘图刷新，而且是24帧以上的刷新率的连续动画。所以简单的主界面上View做不到这些。
我需要的是根据一个二维点阵数组在主界面上绘制像素点。 您这个类库里面有canvas.drawpoint()这个方法么？

**Comment by submarinexu** [comment]
另外说了一下.我是先看到写的《为什么你的canvas这么慢》这篇文章，才了解我的问题所在，谢谢。

**Comment by ChillingVan** [comment]
我在博客里就说了，普通的View就是用硬件加速的，也就是用GPU绘制的。普通的View里的Canvas可以绘制你想要的任何东西。你可以看B站开源的Damaku，弹幕绘制，速度最快的就是用普通View。至于刷新，就要靠你自己多线程异步控制了。

我的这个库更偏向于视频处理不得不使用TextureView和SurfaceView这两种情况的。 绘制像素点，本质是绘制Bitmap，我这个库也可以做到。

**Comment by submarinexu** [comment]
多谢指点！
