### ISSUE TITLE
请问 ,能把一张480的图片生成1280的图片吗

### ISSUE THREAD

**Issue by baiyangyan** [ChillingVan/android-openGL-canvas#26]
请问 ,能把一张480的图片生成1280的图片吗

**Comment by ChillingVan** [comment]
啥意思...

**Comment by baiyangyan** [comment]
我的意思是 原本 640*480 大小的图片,能通过您的canvas  画出1920*1280 的图片吗?或者尺寸更大的图片 , 清晰度不变 ,我之前通过bitmap 的方法将他放大 ,清晰度变模糊了;

**Comment by baiyangyan** [comment]
我的意思是 原本 640   *  480 大小的图片,能通过您的canvas  画出1920    *    1280 的图片吗?或者尺寸更大的图片 , 清晰度不变 ,我之前通过bitmap 的方法将他放大 ,清晰度变模糊了;

**Comment by ChillingVan** [comment]
做不到，任何代码都做不到。

**Comment by baiyangyan** [comment]
好的 谢谢
