### ISSUE TITLE
camera预览时点击home再回来预览画面一定会卡住

### ISSUE THREAD

**Issue by dpmaycry** [ChillingVan/android-openGL-canvas#27]
虽然onResume和onPause有open/release Camera 和    
initCameraTexture();     
       cameraTextureView.onResume();
        previewConsumerTextureView.onResume();
        cameraTextureView.onPause();
        previewConsumerTextureView.onPause();
但似乎没什么卵用
  setOnCreateGLContextListener里的onCreate和
setOnSurfaceTextureSet里的onSet
在第二次onResume的时候都没有调用

**Comment by dpmaycry** [comment]
setOnCreateGLContextListener里的onCreate和
setOnSurfaceTextureSet里的onSet
在第二次onResume的时候都没有调用

**Comment by ChillingVan** [comment]
是TextureCamera那个例子吗？我这边重现不了。有没有其它细节？

**Comment by dpmaycry** [comment]
是的，就是TextureCameraActivity这个类。
app里打开这个类的相机预览，然后home键返回主界面，打开其它应用，再home键打开app，会发现预览画面是暂停的。
我大致看了下发现的原因可能是之前上面提到的，但是不确定。
如果有啥需要实时交流的可以随时加微信 dpmaycry

**Comment by ChillingVan** [comment]
我这边还是找不到原因，也重现不了，而且我这里onSet是有调用的。 可能是机型或系统原因吧。

**Comment by ChillingVan** [comment]
经测试只在4.4上能重现，有空会发一个新版。

**Comment by tssA8** [comment]
Android O 也會遇到
原因是GLSurfaceTextureProducerView.java onResume沒有跑到onSet的Callback導致的.
解決方法:
在CameraPreviewTextureView.java 重新實作onSurfaceChanged

 @Override
    public void onSurfaceChanged(int width, int height) {
        super.onSurfaceChanged(width, height);
        if (_producedRawTexture == null) {
            Log.d("AAA ","_producedRawTexture is null ");
            _producedSurfaceTexture = new SurfaceTexture(1);
            post(new Runnable() {
                @Override
                public void run() {
                    if (onSurfaceTextureSet != null) {
                        onSurfaceTextureSet.onSet(_producedSurfaceTexture, _producedRawTexture);
                    }
                }
            });
        }else {
            _producedRawTexture.setSize(width, height);
        }
    }

private OnSurfaceTextureSet onSurfaceTextureSet;
    public interface OnSurfaceTextureSet {
        void onSet(SurfaceTexture surfaceTexture, RawTexture surfaceTextureRelatedTexture);
    }
    public void setOnSurfaceTextureSet(OnSurfaceTextureSet _onSurfaceTextureSet) {
        onSurfaceTextureSet = _onSurfaceTextureSet;
    }

並在onPause的地方把_producedRawTexture清空
public void clearProducedRawTexture(){
        if(_producedRawTexture!=null){
            _producedRawTexture = null;
        }
        if (_producedSurfaceTexture != null) {
            _producedSurfaceTexture = null;
        }
    }

**Comment by ChillingVan** [comment]
@tssA8 请问现在用的是最新的1.2.2.2版本吗？这个问题前两天应该改好了，

**Comment by tssA8** [comment]
了解,還是用v1.2.2.1

感謝
