### ISSUE TITLE
关于glcanvas中glpaint的绘制图像像素不饱满问题

### ISSUE THREAD

**Issue by dpmaycry** [ChillingVan/android-openGL-canvas#28]
比如用glpaint画一个方框，会发现4个角的部分有几个像素的空白
看上去就像是没画到位
不知道是不是没有抗锯齿的缘故

**Comment by ChillingVan** [comment]
我用CompareCanvasActivity试了一下，然后截图，没有发现。能截图上传看看吗？
![image](https://user-images.githubusercontent.com/7666419/34916297-eb8a7b42-f970-11e7-9fbe-c63f884bedd8.png)

**Comment by dpmaycry** [comment]
你看图里的绿色矩形，四角的像素没画到位，每个角都空了几个像素。

**Comment by ml-bright** [comment]
这个应该是锯齿吧

**Comment by ChillingVan** [comment]
这个是OpenGL的一个坑，官方也没有好的提议。我试过开抗锯齿也搞不定..

https://www.opengl.org/archives/resources/faq/technical/rasterization.htm

**Comment by dpmaycry** [comment]
还是手动在4角画4个点吧～～
