### ISSUE TITLE
有配合camera2 api使用的示例么

### ISSUE THREAD

**Issue by dpmaycry** [ChillingVan/android-openGL-canvas#29]
自己写了个camera2的实例，结果textureview可以用，gltextureview黑屏，可能是使用的方式不对

**Comment by ChillingVan** [comment]
能贴代码不？

**Comment by dpmaycry** [comment]
有时间我把代码传hub上

**Comment by Lyzon** [comment]
@dpmaycry hi，你好。我同样遇到这个问题。但是看了你的解决方案我还是不清楚。我是new Surface(mTextureView.getSurfaceTexture()) 的Surface传给RequestBuilder。。。mPreviewRequestBuilder.addTarget(surface);

这样依旧是黑屏，可以详细说一下你是如何解决的吗?
