### ISSUE TITLE
我想问下如果用opengl做动画，除了不断调用GLUtils.texImage2D，还有什么办法？

### ISSUE THREAD

**Issue by a483210** [ChillingVan/android-openGL-canvas#3]
我想问下如果用opengl做动画，除了不断调用GLUtils.texImage2D(GLES20.GL_TEXTURE_2D, 0, mBitmap, 0);
还有什么办法呢？

**Comment by ChillingVan** [comment]
可以参考我的AnimActivity例子。
另外，如果不是有特殊的用 opengl 的要求，可以直接用自定义View，实现onDraw(Canvas)，使用View.invalidate()的方法实现高性能动画。

**Comment by a483210** [comment]
谢谢

**Comment by submarinexu** [comment]
你好,向您提个问题。我现在的APP里面使用安卓自带surfaceview里面的canvas来进行点阵绘图。但是模拟器测量下来，整个绘图过程耗时将近60mS。达不到每秒钟24帧的最低刷新率。查询了一下，surfaceview里面的canvas绘图是没有GPU参与加速的，导致了绘图耗时过大。
网上搜到您写的这个类库，特向您请教，如果使用您这个类库的话是否能实现GPU参与加速的Canvas绘图？
