### ISSUE TITLE
您好，我使用GlTextureView的setRender()方法，GLViewRenderer里的回调没有GL10这个参数吗

### ISSUE THREAD

**Issue by sea5241** [ChillingVan/android-openGL-canvas#31]
您好，我使用GlTextureView的setRender()方法，GLViewRenderer里的回调没有GL10这个参数吗?GLSurfaceView.Renderer里是有的

**Comment by ChillingVan** [comment]
没有，这个库尽量不暴露所有GL相关的东西，会对GL的操作都做封装
