### ISSUE TITLE
v1.2.2.2版本的 CameraPreviewTextureView.setOnSurfaceTextureSet() 會跑兩次

### ISSUE THREAD

**Issue by tssA8** [ChillingVan/android-openGL-canvas#32]
在Android 6.0 samsung S6 以及 Android 8.0 Nexus 5X 都會遇到這個問題
[CameraPreviewTextureView.setOnSurfaceTextureSet() 會跑兩次]
感謝

**Comment by ChillingVan** [comment]
请问一下 GLSurfaceTextureProducerView 里的 onSurfaceChanged 也会跑两次吗？我的6.0手机重现不了

**Comment by ChillingVan** [comment]
8.0的手机也重现不了.. 6.0的是氢OS。 8.0的是EMUI。。

**Comment by tssA8** [comment]
您好,我又測試了幾次發現再的1.2.2.2的版本 ,使用CameraPreviewTextureView調用的onSurfaceChanged會跑兩次的原因是,我使用的CameraPreviewTextureView extends GLSurfaceTextureProducerView之外,**有另外開一個function調用 requestLayout();在機器玄轉時觸發**; 另一方面1.2.2.1版本則不會發生此問題.

不知道這事不是我使用上面的問題

ps:我的手機是android8.0.0  LG Nexus 5x原生系統 ,但不是氢OS;

感謝

**Comment by ChillingVan** [comment]
因为旋转时有大小变化，会触发onSurfaceChange.。你这里也设置了大小，也会触发。我考虑一下多次调用的情况怎么处理producedTexture比较好吧

**Comment by ChillingVan** [comment]
已升级到1.2.2.3，请试试最新版是否可以，谢谢

**Comment by tssA8** [comment]
測試過了,1.2.2.3沒有問題了
謝謝
