### ISSUE TITLE
关于图片播放器的实现

### ISSUE THREAD

**Issue by w2xx** [ChillingVan/android-openGL-canvas#33]
看到之前也有讨论到播放图片，但是还是有些疑问，目前我这边有个功能，就是播放一组图片帧，但是我发觉我如果直接在ongldraw里面去加载bitmap在回收，就会报错。目前我是采用bitmap内存复用，来实现不oom，但是存在个问题，就是textureview里面的图片不刷新，我在界面上写了一个imageview，通过textureview.getBitmap，设置到imageview就是正常的。不知道这里要怎么助理

**Comment by ChillingVan** [comment]
如果bitmap有改变，要用 canvasGL的 invalidateContent去刷新

**Comment by w2xx** [comment]
我目前是在onGLDraw设置bitmap的，具体应该在哪里面调用invalidateContent去刷新呢

**Comment by ChillingVan** [comment]
在drawBitmap之前就可以。可以参考例子，在最新的例子代码上有用到。

**Comment by w2xx** [comment]
看到了，功能已经实现了。。但是我在profiler里面查看内存情况，发现每次进入我写的界面在退出，native内存都会增加一点

**Comment by ChillingVan** [comment]
@w2xx  我的例子里也会这样吗?可以确认是这个库的问题吗?

**Comment by w2xx** [comment]
是的，我看了下，重复打开filterActivity和mediaplayerActivity页面，native内存每次都会比上次上涨几MB。不知道是不是属于正常现象

**Comment by ChillingVan** [comment]
@w2xx 我的机子复现不了...
![image](https://user-images.githubusercontent.com/7666419/38934599-c84dabb8-434e-11e8-9b7c-9db16a606bbb.png)
![image](https://user-images.githubusercontent.com/7666419/38934624-d082ad6a-434e-11e8-9315-bf9eff266876.png)
![image](https://user-images.githubusercontent.com/7666419/38934652-dd5a806c-434e-11e8-80d4-92847de1162b.png)
图片由上到下分别是进入FilterActivity，返回键退出，再次进入

**Comment by w2xx** [comment]
可能是我这边手机的问题，我用的一款国外的机器测得。现在有个小问题就是内存抖动的很严重，我发现这个库已经做了bitmap的回收，但是现在我想自己实现bitmap的复用和回收，需要怎么操作呢

**Comment by ChillingVan** [comment]
我这边管理的只是Texture的内存，对bitmap是不管的。

**Comment by w2xx** [comment]
嗯，明白了。多谢了，终于找到我这边内存抖动的原因了，解析bitmap的方式有问题。还是很感谢你的这个库，很棒，加油！
