### ISSUE TITLE
HorizontalScrollView包含GLTexutView的时候有时候没有进行渲染

### ISSUE THREAD

**Issue by yudapiandroid** [ChillingVan/android-openGL-canvas#34]
GLTexutView的高度小于 443px 的时候没有渲染
GLTexutView的高度大于 444px 的时候会进行渲染
机型是 荣耀8

**Comment by yudapiandroid** [comment]
<HorizontalScrollView
        android:background="#ff0"
        android:layout_width="match_parent"
        android:layout_height="wrap_content">
        <com.suse.dapi.tableview.GLTexutDemoView
            android:layout_width="match_parent"
            android:layout_height="300px" />
    </HorizontalScrollView>

<HorizontalScrollView
        android:background="#ff0"
        android:layout_width="match_parent"
        android:layout_height="wrap_content">
        <com.suse.dapi.tableview.GLTexutDemoView
            android:layout_width="match_parent"
            android:layout_height="500px" />
    </HorizontalScrollView>

**Comment by yudapiandroid** [comment]
<HorizontalScrollView
        android:background="#ff0"
        android:layout_width="match_parent"
        android:layout_height="wrap_content">
        <com.suse.dapi.tableview.GLTexutDemoView
            android:layout_width="match_parent"
            android:layout_height="500px" />
    </HorizontalScrollView>

**Comment by ChillingVan** [comment]
所以是没问题了吗？
