### ISSUE TITLE
关于GPUImageLookupFilter问题

### ISSUE THREAD

**Issue by xsb0426** [ChillingVan/android-openGL-canvas#35]
能不能实现一下gpuimage里面的GPUImageLookupFilter这个滤镜，根据你的demo自己试了一下，滤镜效果不对，下面是我根据你的格式自己写的滤镜，用4*4的色彩立方图
`public class LookupFilter extends TwoTextureFilter {

    private float mIntensity = 1.0f;

    private static final String LOOKUP_FRAGMENT_SHADER =
            "varying highp vec2 " + VARYING_TEXTURE_COORD + ";\n" +
                    " varying highp vec2 " + VARYING_TEXTURE_COORD2 + "; // TODO: This is not used\n" +
                    " \n" +
                    " uniform sampler2D " + TEXTURE_SAMPLER_UNIFORM + ";\n" +
                    " uniform sampler2D " + UNIFORM_TEXTURE_SAMPLER2 + "; // lookup texture\n" +
                    " \n" +
                    " uniform lowp float intensity;\n" +
                    " \n" +
                    " void main()\n" +
                    " {\n" +
                    "     highp vec4 textureColor = texture2D(" + TEXTURE_SAMPLER_UNIFORM + ", " + VARYING_TEXTURE_COORD + ");\n" +
                    "     \n" +
                    "     highp float blueColor = textureColor.b * 15.0;\n" +
                    "     \n" +
                    "     highp vec2 quad1;\n" +
                    "     quad1.y = floor(floor(blueColor) / 4.0);\n" +
                    "     quad1.x = floor(blueColor) - (quad1.y * 4.0);\n" +
                    "     \n" +
                    "     highp vec2 quad2;\n" +
                    "     quad2.y = floor(ceil(blueColor) / 4.0);\n" +
                    "     quad2.x = ceil(blueColor) - (quad2.y * 4.0);\n" +
                    "     \n" +
                    "     highp vec2 texPos1;\n" +
                    "     texPos1.x = (quad1.x * 0.25) + 0.5/64.0 + ((0.25 - 1.0/64.0) * textureColor.r);\n" +
                    "     texPos1.y = (quad1.y * 0.25) + 0.5/64.0 + ((0.25 - 1.0/64.0) * textureColor.g);\n" +
                    "     \n" +
                    "     highp vec2 texPos2;\n" +
                    "     texPos2.x = (quad2.x * 0.25) + 0.5/64.0 + ((0.25 - 1.0/64.0) * textureColor.r);\n" +
                    "     texPos2.y = (quad2.y * 0.25) + 0.5/64.0 + ((0.25 - 1.0/64.0) * textureColor.g);\n" +
                    "     \n" +
                    "     lowp vec4 newColor1 = texture2D(" + UNIFORM_TEXTURE_SAMPLER2 + ", texPos1);\n" +
                    "     lowp vec4 newColor2 = texture2D(" + UNIFORM_TEXTURE_SAMPLER2 + ", texPos2);\n" +
                    "     \n" +
                    "     lowp vec4 newColor = mix(newColor1, newColor2, fract(blueColor));\n" +
                    "     gl_FragColor = mix(textureColor, vec4(newColor.rgb, textureColor.w), intensity);\n" +
                    " }";

    public LookupFilter(@NonNull Bitmap secondBitmap) {
        super(secondBitmap);
    }

    @Override
    public String getFragmentShader() {
        return LOOKUP_FRAGMENT_SHADER;
    }

    @Override
    public void onPreDraw(int program, BasicTexture texture, ICanvasGL canvas) {
        super.onPreDraw(program, texture, canvas);
        int mIntensityLocation = GLES20.glGetUniformLocation(program, "intensity");
        OpenGLUtil.setFloat(mIntensityLocation, mIntensity);
    }

    public void setValue(@FloatRange(from = 0.0, to = 1.0f) final float intensity) {
        mIntensity = intensity;
    }
}`

**Comment by ChillingVan** [comment]
我改了几个数值，似乎和GPUImage效果一样。已更新代码，请查看。

**Comment by xsb0426** [comment]
谢谢你！！！问题解决了！ 原来上面的4*4色彩立方图代码是对的，是因为我偷懒直接把色彩立方图放在drawable目录下所以效果不对，我把立方图放在drawable-nodpi下面效果就对了，GpuImage里面的色彩立方图是8*8的，所以你需要改数值，总之谢谢！！！
