### ISSUE TITLE
关于图片平移时抖动问题 

### ISSUE THREAD

**Issue by lh414035210** [ChillingVan/android-openGL-canvas#38]
作者您好，最最近我在使用opengles2.0 做一个图片平移的效果，在广告板子上面抖动的厉害，您能指教一下么

**Comment by ChillingVan** [comment]
能提供demo代码或者gif图吗？

**Comment by lh414035210** [comment]
哈哈，肯定可以啊。不过我现在身边没电脑.你加下我qq吧，我发给你.414035210

**Comment by ChillingVan** [comment]
啊，我以为和本项目相关..... 以后与本项目无关的不要在这里提。

另外略微看了你的源码，抖动的原因可能是在marqueeLeft，marqueeRight等大量使用System.arraycopy方法。
