### ISSUE TITLE
用多张图片输出成视频可以用这个实现吗

### ISSUE THREAD

**Issue by WangShuo1143368701** [ChillingVan/android-openGL-canvas#40]
请问作者，这个库可以实现类似抖音把多张图片输出成视频，视频效果是每张图片显示两秒左右，图片之间的切换有滑动效果。或者提供下思路 0.0

**Comment by ChillingVan** [comment]
可以参考这个https://github.com/ChillingVan/AndroidInstantVideo的例子。
或者自己反编译抖音..
