### ISSUE TITLE
Is it possible to crop while using drawSurfaceTexture ?

### ISSUE THREAD

**Issue by inventionsbyhamid** [ChillingVan/android-openGL-canvas#42]
I want to crop camera preview to square while drawing. Providing square coordinates to drawSurfaceTexture the camera preview appears slightly stretched. I am drawing the camera preview on a certain portion of textureview and cannot use the normal technique of resizing the actual view or setting a scale transform on view etc. How to extend GLES20Canvas to include crop functionality?

**Comment by ChillingVan** [comment]
Currently I think up two solution:
1. Make your texture view smaller than your texture, then the part you don't want is hided.
2. Write a new texture filter. Draw transparent color at the part you do not want.
In the texture filter, the image area is 0.0, 0.0 - 1.0, 1.0.
So when you want to crop the left and top 1/4 area of the image, you can add code like:
if (x > 0.5 || y > 0.5) {
  gl_FragColor = vec4(0, 0, 0, 0);
}

What do you think?

**Comment by inventionsbyhamid** [comment]
Option 2 seems more favourable since it can easily be used in case of multiple textures. I wanted to achieve a center crop on camera preview but have not been able to write the fragment shader since I have just started out learning OpenGL. So if texture is 640x480 and required size is 200x200 then the fragment shader should color the entire portion remaining (Basically 4 rectangles)? except the center 200x200 ?

**Comment by ChillingVan** [comment]
@inventionsbyhamid  Yes, it will cover all the 640*480. The coordinate in fragment shader of texture is from 0.0 - 1.0, both in x and y coordinate.  
Then in your example the area is:
left -> 640/2 - 200/2 = 220 --> 220/640 = 0.3475
right -> 640/2 + 200/2 = 420 --> 420/640 = 0.65625
top -> 480/2 - 200/2 = 140 --> 140/480 =0.29167
bottom -> 480/2 + 200/2 = 340 --> 340/480 = 0.70833
if(left < x < right && top < y < bottom) {
  gl_FragColor =texture2D(" + TEXTURE_SAMPLER_UNIFORM + ", " + VARYING_TEXTURE_COORD + "); ;
} else {
  gl_FragColor = vec4(0, 0, 0, 0);
}
Notice the coord may upside down.(I am not sure. I need some test because I forget how the coord works)
I will have a try to write this in these days. If you write it first please make a PR. Thanks.

**Comment by inventionsbyhamid** [comment]
I am not sure but using this fragment shader I am getting everything transparent

CROP_FRAGMENT_SHADER = ""
                + "precision mediump float;\n"+
                "varying vec2 " + VARYING_TEXTURE_COORD + ";\n"
                + "uniform float " + ALPHA_UNIFORM + ";\n"
                + "uniform " + SAMPLER_2D + " " + TEXTURE_SAMPLER_UNIFORM + ";\n"+
                "void main() {\n"
                + "if(gl_FragCoord.x > "+left+" && gl_FragCoord.x  < "+ right + " && gl_FragCoord.y > "+ top +" && gl_FragCoord.y < "+ bottom +") {"
                + "  gl_FragColor = texture2D(" + TEXTURE_SAMPLER_UNIFORM + ", " + VARYING_TEXTURE_COORD + ");\n"
                +"} else {"
                + "  gl_FragColor = " + "vec4(0, 0, 0, 0)" + ";\n"
                +"}"
                + "}\n";

also I am not sure if this will solve the stretching problem? It will center crop but wouldn't the center portion still seem stretched? TextureView size 1080x1350, Camera preview 640x480, camera preview drawn on top left of texture view 200x200

**Comment by ChillingVan** [comment]
The gl_FragCoord should be VARYING_TEXTURE_COORD.
And what is your left, right, top from? They should bind to OpenGL uniform with GLES20.glGetUniformLocation. You can check ContrastFilter as example

**Comment by inventionsbyhamid** [comment]
For testing I have hardcoded the left, right,top, bottom values. Also gl_FragCoord is already defined in fragment shader or should I define it again?

**Comment by ChillingVan** [comment]
I do not get it why stretch? Do you set correct left top right bottom to drawBitmap() ?

Here is an example I just wrote 
```
public class CropFilter extends BasicTextureFilter {


    private static final String CROP_FRAGMENT_SHADER = ""
            + "precision mediump float;\n"
            + "varying vec2 " + VARYING_TEXTURE_COORD + ";\n"
            + "uniform float " + ALPHA_UNIFORM + ";\n"
            + "uniform " + SAMPLER_2D + " " + TEXTURE_SAMPLER_UNIFORM + ";\n"
            + "void main() {\n"
            + "if( "+ VARYING_TEXTURE_COORD + ".x > " + 0.2 + " &&  "+ VARYING_TEXTURE_COORD + ".x < " + 0.7 + " &&  "+ VARYING_TEXTURE_COORD + ".y > " + 0.3 + " &&  "+ VARYING_TEXTURE_COORD + ".y < " + 0.6 + ") {"
            + " gl_FragColor = texture2D(" + TEXTURE_SAMPLER_UNIFORM + ", " + VARYING_TEXTURE_COORD + ");\n"
            + "} else {"
            + " gl_FragColor = " + "vec4(0, 0, 0, 0)" + ";\n"
            + "}"
            + "}\n";


    @Override
    public String getFragmentShader() {
        return CROP_FRAGMENT_SHADER;
    }
}
```

![image](https://user-images.githubusercontent.com/7666419/42329579-9350e2da-80a3-11e8-8df1-040f054ae63e.png)

**Comment by inventionsbyhamid** [comment]
Texture view size is 1080x1350 and camera preview size is 640x480 I guess this is why the camera preview appears stretched. Further I am drawing the camera preview top left 200x200.

**Comment by inventionsbyhamid** [comment]
I have created a sample repo using AndroidInstantVideo to show what I meant by camera stretching. Open TestMp4MuxerActivity and point the camera to a bottle or can to easily see the bottle shorter in length. I want to remove that without applying transforms to textureview since I have other videos rendered on the same textureview. 

https://github.com/inventionsbyhamid/camera_issue

**Comment by ChillingVan** [comment]
So you should crop 200*200 but draw the camera preview as its size

**Comment by ChillingVan** [comment]
OK, I will see that tomorrow, night.

**Comment by inventionsbyhamid** [comment]
I have been able to fix the camera preview shortening issue by scaling the texture coordinates of camera preview in the vertex shader. (I have added this in CropFilter of my sample repo) If I don't crop using the fragment shader then the left and right portion of camera preview becomes distorted and proper camera preview is rendered in center. My end goal is to render the camera preview(maximum possible and center cropped) according to aspect ratio in the coordinates I pass to drawSurfaceTexture.

**Comment by ChillingVan** [comment]
I also solve it by switch the width and height and change the texture view size to camera previe size(640*480).
Origin:
```
canvasGL.drawSurfaceTexture(outsideTexture, outsideSurfaceTexture, 0, height/2, width/2, height, textureFilterLT);
```
Now:
```
        canvasGL.drawSurfaceTexture(outsideTexture, outsideSurfaceTexture, 0, 0, height, width, textureFilterLT);
```

I will do more research.

**Comment by ChillingVan** [comment]
I found it and it is related to the camera orientation. In InstantVideoCamera you can use setDisplayOrientation to set the orientation of camera. And if you set it to 0, and set the texture size to the camera preview size, then you draw it as its preview size, the stretch issue gone.
