### ISSUE TITLE
一个页面绘制数千张 bitmap 的问题

### ISSUE THREAD

**Issue by jinfatimay** [ChillingVan/android-openGL-canvas#43]
如题，需要画数千张 bitmap（bitmap 没那么多，大约十几种，但会需要画几千甚至上万次 drawBitmap），并且需要随著 touch event 做一些画面上的反馈（例如画面移到定点部分 bitmap 需要有动画效果等），好似直接用 View 硬体加速或是用您的 openGL canvas 去画都在移动时还是会有所卡顿，想问问看是否有些建议或解法，感激不尽。

**Comment by ChillingVan** [comment]
能用methrod tracing分析一下是哪一部分耗时吗？

**Comment by jinfatimay** [comment]
`onGLDraw()` 总共画了 3.2 秒
`com.chillingvan.canvasgl.CanvasGL` 的 `drawBitmap` 18.55%
```
@Override
  public void drawBitmap(Bitmap bitmap, Rect src, RectF dst) {
    drawBitmap(bitmap, new RectF(src), dst, basicTextureFilter);
}
```
> 会是 new RectF(src) 的原因吗？

`com.chillingvan.canvasgl.glcanvas.GLES20Canvas.drawTexture() -> drawTextureRect()` 的 `draw()` 本身跟其呼叫到的 `setMatrix()` 都会 call `checkError` 其中分别耗时 16.81% 以及 3.43%
```
private void draw(ShaderParameter[] params, int type, int count, float x, float y, float width,
                      float height, ICustomMVPMatrix customMVPMatrix) {
  setMatrix(params, x, y, width, height, customMVPMatrix);
  int positionHandle = params[INDEX_POSITION].handle;
  GLES20.glEnableVertexAttribArray(positionHandle);
  checkError();
  GLES20.glDrawArrays(type, 0, count);
  checkError();
  GLES20.glDisableVertexAttribArray(positionHandle);
  checkError();
}
```
```
private void setMatrix(ShaderParameter[] params, float x, float y, float width, float height, ICustomMVPMatrix customMVPMatrix) {
  if (customMVPMatrix != null) {
    GLES20.glUniformMatrix4fv(params[INDEX_MATRIX].handle, 1, false, customMVPMatrix.getMVPMatrix(mScreenWidth, mScreenHeight, x, y, width, height), 0);
    checkError();
    return;
  }
  GLES20.glViewport(0, 0, mScreenWidth, mScreenHeight);
  Matrix.translateM(mTempMatrix, 0, mMatrices, mCurrentMatrixIndex, x, y, 0f);
  Matrix.scaleM(mTempMatrix, 0, width, height, 1f);
  Matrix.multiplyMM(mTempMatrix, MATRIX_SIZE, mProjectionMatrix, 0, mTempMatrix, 0);
  GLES20.glUniformMatrix4fv(params[INDEX_MATRIX].handle, 1, false, mTempMatrix, MATRIX_SIZE);
  checkError();
}
```
```
public static void checkError() {
  int error = GLES20.glGetError();
  if (error != 0) {
    Throwable t = new Throwable();
    Log.e(TAG, "GL error: " + error, t);
  }
}
```
> 耗时百分比都全在 `GLES20.glGetError` 上

`com.chillingvan.canvasgl.glcanvas.GLES20Canvas.drawTexture() -> drawTextureRect()` 的 `prepareTexture()` 本身跟其呼叫到的 `enableBlending()` 也跟上面的 `draw()` 一样都会 call `checkError` 其中分别耗时 14.39% 以及 3.42%
> 一样耗时百分比都全在 `GLES20.glGetError` 上

至于 `drawTextureRect()` 自己本身呼叫到的 `checkError()` 一样耗时 3%

`com.chillingvan.canvasgl.glcanvas.GLES20Canvas.drawTexture() -> setupTextureFilter()` 的 `UniformShaderParameter` 以及 `AttributeShaderParameter` 两个 class 里的 `loadHandle`
```
handle = GLES20.glGetUniformLocation(program, mName);  <=== 12.49%
checkError();  <=== 10.16%
```
```
handle = GLES20.glGetAttribLocation(program, mName); <=== 3.77%
checkError();  <=== 2.21%
```

主要是这些，其他的占比很小就不详列，麻烦您了。

**Comment by ChillingVan** [comment]
请问3.2秒里drawBitmap调用了多少次？帧率能达到60帧吗？Bitmap有多大？除了这18.55%，剩下的耗时在哪？能直接上传method tracing的文件吗？

**Comment by ChillingVan** [comment]
Android Studio的话应该在capture文件夹。也可以在代码里用Debug.startMethodTracing用代码来触发，更精准。不过哪一种都会降低手机运行速度。
bitmap不大，按理说应该无压力的。60帧就是每秒60次，5000次3.2秒，好像没什么问题啊。

**Comment by jinfatimay** [comment]
emmm 是一次调用 onGLDraw 就会在里面调用 canvas.drawBitmap() 5000 次（甚至到一两万次）
所以按你所述需要 60 帧的话，会需要每秒能够执行 60 次的 onGLDraw 才能达到。
简单换算一下 60 * 5000 = 300000，也就是每秒需要调用 canvas.drawBitmap() 30 万次

**Comment by ChillingVan** [comment]
所以每一帧要画5000张bitmap？为什么？这个硬件上就不大可能不卡啊

**Comment by jinfatimay** [comment]
emm 你可以看成同时要有 5000 个人物要在画面上动作

**Comment by ChillingVan** [comment]
300×300的图片，5000张，肯定不会显示全吧，能让不能显示的bitmap就不绘制吗？

**Comment by jinfatimay** [comment]
画面可以很即时得放大与缩小，会有显示所有图片的时候

**Comment by ChillingVan** [comment]
这个，似乎是游戏？试过在Unity等游戏引擎上实现类似效果吗？

**Comment by jinfatimay** [comment]
并不是游戏，整个专案只有一个页面需要这样，而且并不需要物理效果，不过有用别的专案试过用 box2d 画 5000 次看看，不知道是不是处理有问题，一样很卡。
目前已经跟设计部门沟通，稍微改了一下需求，大概暂时绕开了这个问题。
