### ISSUE TITLE
crash on API15

### ISSUE THREAD

**Issue by samychen** [ChillingVan/android-openGL-canvas#44]
my phone crash and show createContext failed: EGL_BAD_CONFIG on API15

**Comment by ChillingVan** [comment]
Could you provide the detail log and your phone detail? Does all the samples crash or only one of them crash?

**Comment by samychen** [comment]
01-09 00:37:16.325 13405-13405/? E/BaseGLTextureView: freshSurface() called with: width = [720], height = [996]
01-09 00:37:16.325 13405-13420/? E/GLThread: starting tid=3234
    noticed surfaceView surface lost tid=3234
01-09 00:37:16.325 13405-13405/? E/GLThread: surfaceCreated tid=3234
01-09 00:37:16.325 13405-13420/? E/GLThread: noticed surfaceView surface acquired tid=3234
    guardedRun:readyToDraw 
    chooseConfig: 
    exiting tid=3234
01-09 00:37:16.325 13405-13420/? W/dalvikvm: threadid=11: thread exiting with uncaught exception (group=0x40a351f8)
01-09 00:37:16.333 13405-13420/? E/AndroidRuntime: FATAL EXCEPTION: GLThread 3234
    java.lang.RuntimeException: createContext failed: EGL_BAD_CONFIG
        at com.ufotosoft.facetune.gles.EglHelper.throwEglException(EglHelper.java:212)
        at com.ufotosoft.facetune.gles.EglHelper.throwEglException(EglHelper.java:203)
        at com.ufotosoft.facetune.gles.EglHelper.start(EglHelper.java:75)
        at com.ufotosoft.facetune.gles.GLThread.guardedRun(GLThread.java:232)
        at com.ufotosoft.facetune.gles.GLThread.run(GLThread.java:109)
01-09 00:37:16.567 13405-13405/? D/OpenGLRenderer: Flushing caches (mode 0)
01-09 00:37:16.590 13405-13405/? E/tag: onDestroy: surface
    onDestroy: 
    onPause tid=3234
01-09 00:37:16.590 13405-13405/? E/BaseGLTextureView: onDetachedFromWindow: 
01-09 00:37:16.590 13405-13405/? E/GLThread: requestExitAndWait: 
01-09 00:37:16.590 13405-13405/? E/tag: onSurfaceTextureDestroyed: 
01-09 00:37:16.590 13405-13405/? E/GLThread: surfaceDestroyed tid=3234
    requestExitAndWait: 
01-09 00:37:16.598 13405-13405/? E/libEGL: call to OpenGL ES API with no current context (logged once per thread)

**Comment by ChillingVan** [comment]
Thanks.
It seems it is egl config issue.
Maybe the GLThread.SimpleEGLConfigChooser is not compatible for you phone.

But the config is just the same as GLView
```
setEGLConfigChooser(8, 8, 8, 8, 16, 0);
```

So could you try whether GLView work?

**Comment by samychen** [comment]
it does't work for me. finally i solve it by copy some source code from GLSurfaceView and setEGLConfigChooser(5, 6, 5, 8, 0, 0) in API 15 and API16
