### ISSUE TITLE
GlTextureView的OnTouch问题

### ISSUE THREAD

**Issue by badtea** [ChillingVan/android-openGL-canvas#45]
没错又是我啊，哈哈，请问作者，我在初始化的时候用canvas画了一个Bitmap（new Canvas(Bitmap)）,然后在OnTouch里面初始化了path，用上面的OnTouchMove canvas.DrawPath.但是在onGLDraw 用ICanvasGL draw 上面的Bitmap却没有更新，但是在初始化的时候bitmap的canvas.DrawPath是可以的显示的。onGLDraw正常，一直刷新，只是上面的bitmap没有更新内容

**Comment by ChillingVan** [comment]
https://github.com/ChillingVan/android-openGL-canvas/wiki/CanvasGL

看看这个，可能有帮助

**Comment by badtea** [comment]
可惜的是CanvasGl没有drawPath的方法

**Comment by ChillingVan** [comment]
啊，能力有限，支持不了

**Comment by badtea** [comment]
额。主要奇怪的是bitmap为什么没有更新，命名已经用了canvas通过ontouch画了东西上去了但是在onGlDraw 用ICanvasGL drawBitmap没有更新，作者有思路吗

**Comment by ChillingVan** [comment]
你的bitmap改变了吗？改变了后用invalidateContent(Bitmap bitmap)这个方法刷新后，再canvasGL.drawBitmap也不行？

**Comment by badtea** [comment]
可以了，非常感谢，我直接在onGlDraw 用里面的ICanvasGL.invalidateContent可以了

**Comment by badtea** [comment]
很可惜非常慢。我不知道为什么，我是在ontouch canvas(普通)画path，在ICanvasGL.invalidateContent（bitmap）,画线非常慢,比用textureView 直接用canvas.drawPath

**Comment by badtea** [comment]
public class GlBoard extends GLTextureView {
    /**
     * 屏幕参数
     **/
    int screenWidth, screenHight;
    float[] screenCenterPoint;
    Canvas TCanvas;
    SuLine line;
    private Bitmap bitmapShow,bitmapShow2;
    private boolean isStart=false;
    GLPaint glPaint;
    private IAndroidCanvasHelper drawTextHelper = IAndroidCanvasHelper.Factory.createAndroidCanvasHelper(IAndroidCanvasHelper.MODE.MODE_ASYNC);
    public GlBoard(Context context) {
        super(context);
        setOpaque(false);
        initLine();
    }

    void initLine() {
        line = new SuLine();
        glPaint=new GLPaint();

        glPaint.setStyle(Paint.Style.STROKE);
        glPaint.setLineWidth(5);
        glPaint.setColor(Color.YELLOW);

    }

    public GlBoard(Context context, AttributeSet attrs) {
        super(context, attrs);
        setOpaque(false);
        initLine();
    }

    public GlBoard(Context context, AttributeSet attrs, int defStyleAttr) {
        super(context, attrs, defStyleAttr);
        setOpaque(false);
        initLine();
    }


    public void setScreen(int screenWidth, int screenHight) {
        this.screenWidth = screenWidth;
        this.screenHight = screenHight;
        screenCenterPoint = new float[]{screenWidth / 2, screenHight / 2};
        bitmapShow = Bitmap.createBitmap(screenWidth, screenHight, Bitmap.Config.ARGB_8888);
        TCanvas = new Canvas(bitmapShow);


    }
    float[] startPoint = new float[2];
    float[] endPoint = new float[2];
    @Override
    protected void onGLDraw(ICanvasGL canvas) {
        canvas.save();
        canvas.invalidateTextureContent(bitmapShow);
        canvas.drawBitmap(bitmapShow,0,0);
        canvas.restore();


    }

    @Override
    public void onSurfaceChanged(int width, int height) {
        super.onSurfaceChanged(width, height);
        drawTextHelper.init(width, height);
    }
    @Override
    protected int getRenderMode() {
        return GLThread.RENDERMODE_CONTINUOUSLY;
    }
    @Override
    public boolean onTouchEvent(MotionEvent event) {
        switch (event.getAction()) {
            case MotionEvent.ACTION_DOWN:
                startPoint[0] = (int) event.getX(0);
                startPoint[1] = (int) event.getY(0);
                line=new SuLine();
                line.setBegin(new float[]{startPoint[0], startPoint[1], 0, -9999, -9999, -9999, -9999});
                line.addTouchPoint(new float[]{event.getX(0), event.getY(0), 0, -9999, -9999, -9999, -9999});
                line.DoDraw(TCanvas);
                final MotionEvent event1=event;


                break;
            case MotionEvent.ACTION_MOVE:
                Log.v("ACTION_MOVE",event.getX()+":"+event.getY());
                endPoint[0] = ((event.getX() + startPoint[0]) / 2);
                endPoint[1] = ((event.getY() + startPoint[1]) / 2);
                line.addPoint(new float[]{startPoint[0], startPoint[1], 0, -9999, -9999, -9999, -9999}, new float[]{endPoint[0], endPoint[1], 0, -9999, -9999, -9999, -9999});
                line.addTouchPoint(new float[]{event.getX(), event.getY(), 0, -9999, -9999, -9999, -9999});
                startPoint[0] = event.getX();
                startPoint[1] = event.getY();
                line.DoDraw(TCanvas);
                break;
            case MotionEvent.ACTION_UP:
                line.addPoint(new float[]{startPoint[0], startPoint[1], 0, -9999, -9999, -9999, -9999}, new float[]{startPoint[0], startPoint[1], 0, -9999, -9999, -9999, -9999});
                line.DoDraw(TCanvas);
                break;
        }
        return true;
    }
}

**Comment by badtea** [comment]
上面的代码的line就是一个path。感谢作者，作者能否指点一下

**Comment by ChillingVan** [comment]
@badtea 在AnimActivity里，也用到了restore 和 save。并不慢啊
···
    public void normalDraw(Canvas canvas) {
        canvas.save();
        int left = (int) (point.x - bitmap.getWidth() / (float)2);
        int top = (int) (point.y - bitmap.getHeight() / (float)2);

        canvas.rotate(rotateDegree, point.x, point.y);
        canvas.drawBitmap(bitmap, left, top, paint);

        canvas.restore();
    }
···

**Comment by ChillingVan** [comment]
@badtea 当然，invalidateTextureContent是相对慢的，最好只有bitmap更新时才调用

**Comment by badtea** [comment]
更新速度跟不上ontouchMove的速度，onTouchMove已经绘制了bitmap了，但是更新太慢了

**Comment by ChillingVan** [comment]
对，所以要在onTouch里调用invalidateTextureContent
