### ISSUE TITLE
视频编辑

### ISSUE THREAD

**Issue by w2xx** [ChillingVan/android-openGL-canvas#47]
你好，我现在需要做个功能是对媒体文件二次编辑，然后保存新文件。。但是我这边渲染都是基于纹理做的，不知道这个框架是否能获取到视频每一帧的纹理id呢

**Comment by ChillingVan** [comment]
纹理不会每一帧一个的，只会把每一帧画面都绑定到同一个纹理里。例如在TextureView的onSurfaceTextureAvailable里，它的surface就只包含一个texture。new SurfaceTexture(rawTexture.getId())也只会传一个texture id进去。

**Comment by w2xx** [comment]
。。我看框架中有播放mp4文件的控件，但是回调是个icanvas和surfacetexture，如果我需要对这个视频帧做二次处理，在展示到surface中，该怎么操作

**Comment by ChillingVan** [comment]
用icanvas就可以在视频帧上画想画的东西了。另外视频帧也是icanvas画上去的。

**Comment by w2xx** [comment]
哦。因为我们这边目前只做到实时滤镜，也就是对纹理ID或者视频帧的byte[]去做处理，能具体说下怎么通过icanvas画上去吗

**Comment by ChillingVan** [comment]
MediaCodec 会提供一个 getInputSurface，把这个surface传入offscreenCanvas就可以在上面绘制任意东西了

**Comment by w2xx** [comment]
了解了，多谢。我去试试
