### ISSUE TITLE
How to use GPUImage Filter on this Project?

### ISSUE THREAD

**Issue by hiepgaf** [ChillingVan/android-openGL-canvas#48]
Hi @ChillingVan, thank for great project.

I want to integrate filters from GPUIMage like Amaro, Antique .. How to do?

**Comment by ChillingVan** [comment]
Hi, you can imitate the TextureFilter that have been written in this project and refer to the filters in GPUImage. See the sample FilterActivity.  If you have add some new TextureFilter, PRs are welcomed.
