### ISSUE TITLE
关于图片放大绘制上去图片一部分无法显示

### ISSUE THREAD

**Issue by bflyff** [ChillingVan/android-openGL-canvas#53]
在使用您的一下方法时发现
`void drawBitmap(Bitmap bitmap, @NonNull CanvasGL.BitmapMatrix matrix);`
当图片放大到其宽度或高度超过屏幕的宽度或高度后，再增加放大倍数时到一定值后（针对每个图片大小不一这个值不一样），先是会出现图片的一部分不能绘制出来，再增大放大倍数后画上去的图片整体消失。
这个问题在GLView和GLTextureView中都存在，我将会将这个问题演示连接邮箱发给你。

**Comment by ChillingVan** [comment]
我简单试了一下，画个超屏幕的很大的画面，没有试出来。
从视频来看，初步觉得是某一时刻它的矩阵的值出问题了，但不确定是哪里的问题。
初步设想可能需要写一个类似你的视频里那样，将一张图片慢慢放大的demo试试。
你可以尝试一下不旋转，只放大，看会不会出问题。

你可以试试采集一下log，看一下哪里出问题：

打开ICanvasGL
![image](https://user-images.githubusercontent.com/7666419/48417194-198ee400-e78d-11e8-9282-918159792282.png)
可以找到obtainResultMatrix这个方法。
把里面的int viewportW, int viewportH, float x, float y, float drawW, float drawH的各个参数打出来
以及参照printMatrix方法，把各个matrix打出来。
看一下出问题的时候，这些数值会变成怎样。
需要生成文件，可以直接用FileLogger类来打。

**Comment by bflyff** [comment]
因为没有绘制出来的图像主要是原来图片的右下角部分，你可以用这样的方式试一下

bitmapMatrix = new ICanvasGL.BitmapMatrix();
bitmap = BitmapFactory.decodeResource(getResources(),R.mipmap.meizi_01);
bitmapMatrix.translate(sw/4,sh/2);//移动到屏幕左侧方便看右侧图片
float scale = 1f;
bitmapMatrix.translate(-bitmap.getWidth()*scale/2,-bitmap.getHeight()*scale/2);
bitmapMatrix.scale(scale,scale);

canvas.drawBitmap(bitmap,bitmapMatrix);

这样会显示图片偏中间的部分，当放大倍率到一定数值后，我说的那种现象就会出现，我这边用测试如下：
从左到右放大倍率依次是1f，4f，8f，12f，14f:
[cid:68428ae3-7165-4be0-ac02-7e09261afdfe][cid:08161109-17a6-4e47-8882-d9387040dc16][cid:a23d0595-27b6-4b4a-a15c-a03cd5a447ec][cid:86e05134-2064-40e2-80e6-58c86f9fd071][cid:a5ad9a08-ed59-44c3-96de-374cbcdb2dc1]
从12F起图片右侧就开始显示不全了，从14f起图片下边边也开始显示不全
还有就是我这边不熟悉GL相关的东西，所以只能尽量根据你的提示先尝试从log里看看有无异常。
________________________________
发件人: ChillingVan <notifications@github.com>
发送时间: 2018年11月13日 13:46
收件人: ChillingVan/android-openGL-canvas
抄送: bflyff; Author
主题: Re: [ChillingVan/android-openGL-canvas] 关于图片放大绘制上去图片一部分无法显示 (#53)


我简单试了一下，画个超屏幕的很大的画面，没有试出来。
从视频来看，初步觉得是某一时刻它的矩阵的值出问题了，但不确定是哪里的问题。
初步设想可能需要写一个类似你的视频里那样，将一张图片慢慢放大的demo试试。
你可以尝试一下不旋转，只放大，看会不会出问题。

你可以试试采集一下log，看一下哪里出问题：

打开ICanvasGL
[image]<https://user-images.githubusercontent.com/7666419/48417194-198ee400-e78d-11e8-9282-918159792282.png>
可以找到obtainResultMatrix这个方法。
把里面的int viewportW, int viewportH, float x, float y, float drawW, float drawH的各个参数打出来
以及参照printMatrix方法，把各个matrix打出来。
看一下出问题的时候，这些数值会变成怎样。
需要生成文件，可以直接用FileLogger类来打。

―

**Comment by ChillingVan** [comment]
大概找到原因了。因为之前为了支持rotateZ，采用了透视的方式而不是正交的方式。然后当图片太大了，就会超出视野，然后渲染不出来了。
唯一的解决办法就是提供选择透视还是用正交。这个要有时间再写了

**Comment by bflyff** [comment]
找到原因就好，我这里对OpenGL一窍不通，现在只知道一些概念，刚好您的这个库能解决一些我这样小白的入门问题，还是非常感谢的。而且这个库能解决原生Android很多的不足，希望以后继续完善下去。

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________
