### ISSUE TITLE
如何单独提出mCanvas进行绘制？

### ISSUE THREAD

**Issue by petercao** [ChillingVan/android-openGL-canvas#6]
兄弟好，简书上给你留言过了，我的问题是这样：目前你的绘图都是基于xxview,以及在setContentView(xxView)这种方式进行绘制，但我的项目现在需要单独提取mCanvas，并在自定义的多个页面的surface中进行绘制(drawBitmap)，这种很灵活的方式如何去做？我尝试了自定义的View继承GLTextureView并在该view中定义一个draw()方法绘制，是无法实现的，mCanvas始终为空，不知道为啥？具体要咋做？谢谢了先！

**Comment by ChillingVan** [comment]
首先你为什么要用这个canvas？用普通的canvas不可以吗（只是drawBitmap的话性能没有差别）？另外有没有看过我的例子里面是怎么使用 GLTextureView的？在CompareCanvas里有。

**Comment by petercao** [comment]
1.GLTextureView的调用有以下两处：
public abstract class GLContinuousTextureView extends GLTextureView {
public class FilterGLView extends GLTextureView {

2.CompareCanvasActivity 中只有以下一句话：
        setContentView(R.layout.activity_compare_canvas);

3.因为我的绘制很多帧画面，单靠CPU渲染无法实时并且很容易卡顿不连贯，因此希望能够通过openGL的GPU加速做到，目前希望可以把画布GLCanvas拿出来，带上相关的GL上下文,然后可以在任意需要的页面，需要的surface上进行绘制

**Comment by ChillingVan** [comment]
其实Android自带的Canvas本身在4.0后就是用GPU加速的，所以只是为了性能的话没必要我这个，我的CompareCanvasActivity里已经表现了。你可以看看我的例子里什么地方继承地用了GLContinuousTextureView 。CompareCanvasActivity和AnimActivity里面应该已经有了用法
