### ISSUE TITLE
请问camera 上如何使用filtergroup呢

### ISSUE THREAD

**Issue by cat1024** [ChillingVan/android-openGL-canvas#60]
canvas.drawSurfaceTexture(producedRawTexture, producedSurfaceTexture, 0, 0, mViewWidth,mViewHeight,textureFilter);
textureFilter只能是单个滤镜，如果是filtergroup 就没效果，如何兼容到filtergroup

**Comment by ChillingVan** [comment]
谢谢提出这个bug。发现并没有把filterGroup的代码应用到 SurfaceTexture 里。
然后尝试直接用目前的FilterGroup，发现最后输出的图像会多很多白噪点。暂时原因不明。

有另外一个实现方法，就是用多个MutiTexOffscreenCanvas来实现FilterGroup的功能，不过也有点麻烦，有兴趣可以试试

**Comment by cat1024** [comment]
还是希望有更优雅的方式 实现FilterGroup，大佬近期会修复这个问题吗

**Comment by cat1024** [comment]
![图片](https://user-images.githubusercontent.com/24891407/62410641-fa85fa00-b61a-11e9-95d8-9c955e439eca.png)
outputTexture 不为null 时会直接返回 ，没有绘制当前帧，可能就是这里的问题了

**Comment by ChillingVan** [comment]
还不够，你可以看看我在dev分支上的提交，但是显示少了一截并且偶尔会崩。网上关于OES的资料很少，需要一些时间查原因了。

**Comment by ChillingVan** [comment]
问题已修复，可以验证一下

**Comment by cat1024** [comment]
嗯嗯，好的，谢谢
