### ISSUE TITLE
BitmapMatrix  translate  图片会变形？

### ISSUE THREAD

**Issue by cat1024** [ChillingVan/android-openGL-canvas#63]

**Comment by ChillingVan** [comment]
能发一下截图吗？

**Comment by ChillingVan** [comment]
或者说你的例子代码

**Comment by cat1024** [comment]
![图片](https://user-images.githubusercontent.com/24891407/62818157-d3c54780-bb75-11e9-845e-7fbc86ecabcc.png)
![图片](https://user-images.githubusercontent.com/24891407/62818159-daec5580-bb75-11e9-87b1-ff17effb2bc7.png)
CompareGLView 里面的代码， matrix.translate(200, 0);的意思就是x轴平移200像素吗，结果图片会有些变形

**Comment by ChillingVan** [comment]
已于1.4.2.1修复

**Comment by cat1024** [comment]
X轴平移正常了，但是Y轴和x.y同时平移时，依然会有图片拉伸的情况发生

**Comment by cat1024** [comment]
![图片](https://user-images.githubusercontent.com/24891407/63484104-26d1bf80-c4d1-11e9-9a16-547476b32f34.png)
最终修改成这样，就能兼顾x、y 轴

**Comment by cat1024** [comment]
![图片](https://user-images.githubusercontent.com/24891407/63484381-fb9ba000-c4d1-11e9-9870-d057c290b477.png)
最终修改正这样，就能兼顾x/y轴的平移

**Comment by ChillingVan** [comment]
已在v1.4.2.2里修复，谢谢指正
