### ISSUE TITLE
OrthoBitmapMatrix  rotateZ  如何控制旋转中心，目前想让其在图片中心旋转

### ISSUE THREAD

**Issue by ithour** [ChillingVan/android-openGL-canvas#64]

**Comment by ithour** [comment]
BitmapMatrix  translate   图片会有变形现象，代码示例：

 CanvasGL.BitmapMatrix matrix = new CanvasGL.BitmapMatrix();

        matrix.translate(300,0);
        canvas.drawBitmap(baboon, matrix);

**Comment by ChillingVan** [comment]
rotateZ的话要Perspect，不能用Ortho

**Comment by ChillingVan** [comment]
另外一个问题在看

**Comment by ChillingVan** [comment]
已于1.4.2.1修复
