### ISSUE TITLE
有个问题想要请教一下

### ISSUE THREAD

**Issue by cat1024** [ChillingVan/android-openGL-canvas#69]
开启相机加入人脸识别，美颜算法后帧率就会降低很多，onGLDraw5、60毫秒才会回调一次，在这里做一些图片平移动画，canvasGL.drawBitmap(bitmap,left,top);由于帧率低，动画感觉比较卡，有没有办法可以解决这种问题，难道要再起一个surface绘制动画么

**Comment by ChillingVan** [comment]
onGLDraw里有没有耗时的操作？可以知道哪些操作耗时吗？本质上跟Android的onDraw时不能干太多事一样的

**Comment by cat1024** [comment]
耗时的话，人脸识别有些耗时大概耗时20毫秒，这个可以移到onPreviewFrame，然后就是一个美颜磨皮滤镜，也会耗时20毫秒左右

**Comment by ChillingVan** [comment]
滤镜是用什么实现的？GLSL+FilterGroup？能不能优化成只用一个GLSL

**Comment by cat1024** [comment]
滤镜那块是有优化空间，磨皮算法可以优化，不过也比较麻烦，后面也可能加入一些瘦脸等功能，都会有一定计算量，影响帧率，就想着能不能把动画部分跟相机相关的部分分开。或者再开一个线程执行动画的。

**Comment by ChillingVan** [comment]
按你说的叠加两个TextureView是可以的，这样就会分开两个绘制线程。动画的话你看看有没有重的计算，如果没有什么优化空间就还是要分出另外一个View。如果动画什么的不依赖GLSL的话，用Android原生View就可以了，Android原生View所谓的硬件加速内部也是用了OpenGL的

**Comment by cat1024** [comment]
分两个TextureView 如何录制视频呢

**Comment by ChillingVan** [comment]
可以参考例子里的TextureCamera以及另一个项目https://github.com/ChillingVan/AndroidInstantVideo，本质上就是将原始画面交给OffScreenCanvas，然后再用OffScreenCanvas分发不同画面给不同TextureView，再分别做处理。
当然你最好先考量是否必须这样做

**Comment by cat1024** [comment]
嗯嗯，好的，谢谢
