### ISSUE TITLE
向您请教一些问题

### ISSUE THREAD

**Issue by ZhangGuangXin** [ChillingVan/android-openGL-canvas#7]
你好，有几个问题，向您请教一下：
1：你这个library能支持管线编程吗？用户可以自己手动的编写顶点着色器和片段着色器吗？
2：你这个只能用来绘制2D图像吗？能否支持透视投影，光照, blend等效果？

**Comment by ChillingVan** [comment]
不支持...可能你需要的是一个游戏引擎。
至于编写顶点着色器和片段着色器，因为我这里只处理2d图像或者一些简单图形，有不少限制，有需要的话你可以参考名字带filter的类。
