### ISSUE TITLE
BitmapMatrix  rotateZ 图片变形问题

### ISSUE THREAD

**Issue by cat1024** [ChillingVan/android-openGL-canvas#70]
当  translate  x,y 值不一样时，rotateZ  图片会有变形现象

CanvasGL.BitmapMatrix matrix = new CanvasGL.BitmapMatrix();

        matrix.translate(390, 0);
        matrix.rotateZ(45);
        canvas.drawBitmap(baboon, matrix);

        matrix.reset();
        matrix.translate(100, 200);
        matrix.rotateZ(45);
        canvas.drawBitmap(BitmapFactory.decodeResource(getResources(), R.drawable.lenna), matrix);

**Comment by ChillingVan** [comment]
已修复，感谢提出
