### ISSUE TITLE
为什么调用两次 “onDrawFrame(gl)” 呢？

### ISSUE THREAD

**Issue by laomengzhu** [ChillingVan/android-openGL-canvas#72]
https://github.com/ChillingVan/android-openGL-canvas/blob/db454823a7a6d369b1f2f5d95543bbe22451a471/canvasgl/src/main/java/com/chillingvan/canvasgl/glview/GLView.java#L139

**Comment by ChillingVan** [comment]
这个在以前某些机型会有问题，所以需要绘制两次，但是具体哪些机型不确定了，之后如果确认大部分机型可以的话，可以只绘制一次

**Comment by laomengzhu** [comment]
> 这个在以前某些机型会有问题，所以需要绘制两次，但是具体哪些机型不确定了，之后如果确认大部分机型可以的话，可以只绘制一次

谢谢！
