### ISSUE TITLE
關於camera preview 畫面轉角度

### ISSUE THREAD

**Issue by f9021003** [ChillingVan/android-openGL-canvas#74]
你好

請問一下, 我能夠在 TextureCameraActivity 範例中, 將PreviewConsumerTextureView 畫面 轉90度嗎??
我知道 ICanvasGL.drawBitmap() 中 可以透過 matrix設定 轉角度or放大.
但我看ICanvasGL.drawSurfaceTexture() 似乎沒辦法直接轉90度?? 或是有其他方法可以提供呢??

感謝

`void drawSurfaceTexture(BasicTexture texture, @Nullable SurfaceTexture surfaceTexture, int left, int top, int right, int bottom);`

`void drawSurfaceTexture(BasicTexture texture, @Nullable SurfaceTexture surfaceTexture, int left, int top, int right, int bottom, TextureFilter textureFilter);`

**Comment by ChillingVan** [comment]
这个可以考虑这些方法：
1. 使用Camera的方法设定角度： camera.setDisplayOrientation
2. 旋转TextureView：使用View本身的rotate方法

至于drawSurfaceTexture使用bitmapMatrix，我尝试在后续版本加一下

**Comment by f9021003** [comment]
首先非常感謝 @ChillingVan  大 的回覆~~

其實我的應用情境 : 透過camera2 與 mediacode , 將camera影像壓成h264後, 透過網路傳出去 (rtsp)
(類似 AndroidInstantVideo 的範例)
所以 上面@ChillingVan 提出的方法, 可能不太適合我

`1. 使用Camera的方法设定角度： camera.setDisplayOrientation `
我用的是camera2 api...camera2似乎沒有 setDisplayOrientation  可以使用...

`2.旋转TextureView：使用View本身的rotate方法`
因為我是要透過mediacodec encode, 所以必須透過你們的lib中的 OffScreenCanvas or MultiTexOffScreenCanvas  來整合

但由於camera鏡頭 和 螢幕方向, 有轉90度or 270度 的現象,  導致接收端看到的影像會不太正確...
所以依照我的上述情境, 請問 @ChillingVan  還有其他建議嗎??

PS. 我有嘗試 ICanvasGL.rotate(90), 但畫面會一直閃, 似乎不能這樣用???!!


感謝各位

**Comment by ChillingVan** [comment]
`
        canvas.save();
        canvas.rotate(90, producedRawTexture.getWidth()/2, producedRawTexture.getHeight()/2);
        canvas.drawSurfaceTexture(producedRawTexture, producedSurfaceTexture, 0, 0, producedRawTexture.getWidth(), producedRawTexture.getHeight(), textureFilter);
        canvas.restore();
`
我在CameraPreviewTexture里试了一下这样的代码可以。

另外，既然只做encode用途，那么是不是预览的角度就应该和拍摄的角度保持一致呢？这样才能保证后续播放的角度和预览时角度是一致的。

这个链接可能会有帮助：
https://stackoverflow.com/questions/32834746/android-camera2-wrong-rotation

**Comment by f9021003** [comment]
感謝C大~  原來要rotate前, 要先用 save() 和 restore() 包起來, 影像沒問題了~ 
非常感謝

**Comment by TWJessieChen** [comment]
哈摟 ChillingVan ：
我git您的

**Comment by TWJessieChen** [comment]
哈摟 ChillingVan ：
我git您的code，其中在example code的MultiTextureActivity這個範例，
我知道您沒有設定preview 角度，但是一般手機的攝影機預設是90度，
但您的preview所呈現的卻是已經校正完的影像，
我想要請問的是，您是在哪一段code做轉換角度的動作呢？

**Comment by ChillingVan** [comment]
@TWJessieChen 
```
            rawTexture.setIsFlippedVertically(true);
```
可以试一下MultiVideoTexture里的这个。
然后这个例子是用Camera2的。

**Comment by TWJessieChen** [comment]
![device-2019-12-12-100953](https://user-images.githubusercontent.com/6779791/70676759-2d768380-1cc8-11ea-9b7b-f435cc15d67a.png)

我嘗試把這段code給mark掉(rawTexture.setIsFlippedVertically(true);)，
結果呈現是上下顛倒，
並不是手機直向，preview呈現90度轉向方式呈現，
所以想要詢問，是否在GLES20Canvas class中，
是否有把影像給轉270度了，
造成影像變成上下顛倒，
所以我需要從哪個地方下手，
改成不需要多轉到270度，
只要轉個90度就好了!!!
麻煩您了~
