### ISSUE TITLE
GLContinuousTextureView性能问题

### ISSUE THREAD

**Issue by a1266143** [ChillingVan/android-openGL-canvas#76]
我自定义了一个稍微复杂一点的View，继承了GLContinuousTextureView，同样的代码在SurfaceView中运行很流畅，但是在GLContinuousTextureView会时不时肉眼可见的卡一下，但是好处就像您说的:SurfaceView的背景在透明的同时不能在ViewHierarchy之上，但是GLContinuousTextureView可以做到这两者。

**Comment by ChillingVan** [comment]
可以看看将例子中的AnimActivity里的换为TextureView实现试试。如果还是有卡顿问题，可以贴相关代码到这里。
不过从你的描述中，感觉你的应该直接自定义View可能更适合。TextureView主要还是用于视频帧的显示的。

**Comment by a1266143** [comment]
> 可以看看将例子中的AnimActivity里的换为TextureView实现试试。如果还是有卡顿问题，可以贴相关代码到这里。
> 不过从你的描述中，感觉你的应该直接自定义View可能更适合。TextureView主要还是用于视频帧的显示的。

是的，我发现自定义View也可以很好地完成我的需求，谢谢您
