### ISSUE TITLE
请问一下TwoTextureFilter  想扩展一下 传入的不是bitmap 而是 一个textureId，改如何改造呢？

### ISSUE THREAD

**Issue by cat1024** [ChillingVan/android-openGL-canvas#77]

**Comment by kidd3166** [comment]
BitmapTexture bitmapTexture = canvas.bindBitmapToTexture(GLES20.GL_TEXTURE3, secondBitmap);
-->

GLES20.glActiveTexture(GLES20.GL_TEXTURE3);
GLES20.glBindTexture(GLES20.GL_TEXTURE_2D, second.getId());

second 是 RawTexture

**Comment by ChillingVan** [comment]
可以试试将bitmapTexture换成RawTexture，记得调用
```
        if (!rawTexture.isLoaded()) {
            rawTexture.prepare(canvasGL.getGlCanvas());
        }
```
没有试过效果，你先试试

**Comment by ChillingVan** [comment]
已添加相应功能
