### ISSUE TITLE
内存泄漏

### ISSUE THREAD

**Issue by YJ-L-2017** [ChillingVan/android-openGL-canvas#85]
频繁使用Bitmap.createBitmap生成bitmap来显示，会导致内存一直增加

**Comment by ChillingVan** [comment]
里面用的是弱引用，应该是会GC掉的。
并且在CanvasGL对象被GC时也会回收。

之后会考虑能不能加一个接口，方便外部清理

**Comment by ChillingVan** [comment]
已新增一个接口clearTextureCache，方便及时清理内存
[1.5.2](https://github.com/ChillingVan/android-openGL-canvas/releases/tag/v1.5.2.0)
