### ISSUE TITLE
Android5.1 用PorterDuff.Mode.CLEAR清屏导致背景是黑的，而8.0上是透明的

### ISSUE THREAD

**Issue by boringpipo** [ChillingVan/android-openGL-canvas#87]
//滚动文字
class XXX extends GLSurfaceTextureProducerView
。。。。
protected void onGLDraw(ICanvasGL canvas, SurfaceTexture producedSurfaceTexture, RawTexture producedRawTexture,  SurfaceTexture sharedSurfaceTexture,  BasicTexture sharedTexture) {
        isStart =  true;
        
    	super.onGLDraw(canvas, producedSurfaceTexture, producedRawTexture, sharedSurfaceTexture, sharedTexture);
        if (isStart) {
            drawTextHelper.draw(new IAndroidCanvasHelper.CanvasPainter() {
                @Override
                public void draw(Canvas canvas) {
                    
                    canvas.drawColor(backgroundColor, PorterDuff.Mode.CLEAR);
                  
//接下来绘制文字，但背景是黑的

                }
            });
           
        }
        	
            });
            
        }
        Bitmap outputBitmap = drawTextHelper.getOutputBitmap();
        canvas.invalidateTextureContent(outputBitmap);
        canvas.drawBitmap(outputBitmap, 0, 0);
    }

这个问题网上有不少解释，但没有是在使用该开源库的前提条件下
但我也不想放弃使用该开源库
所以请问有解决方法吗

**Comment by ChillingVan** [comment]
试一试PorterDuff.Mode.SRC？因为这个只是对Bitmap做操作。如果不行的话，就要里面的Bitmap回调出来，然后用Bitmap.eraseColor。

不过如果只是用这个库实现一些动画的话，那用普通的View就行，这个库主要还是用于视频渲染，视频输出

**Comment by ChillingVan** [comment]
已将bitmap回调出来，可以用eraseColor。
[v1.5.2](https://github.com/ChillingVan/android-openGL-canvas/releases/tag/v1.5.2.0)
