### ISSUE TITLE
（功能）使用ETC压缩纹理替代PNG, 放弃bitmap显示连续帧图片

### ISSUE THREAD

**Issue by ml-bright** [ChillingVan/android-openGL-canvas#9]
PNG解码（成bitmap）占用时间，导致连续显示渲染帧图片时，较为卡顿，现在考虑使用ETC压缩纹理图片来显示，目前GLCanvas尚未提供该方法，作者可否提供相关用法，万分感谢

**Comment by ChillingVan** [comment]
能在开始渲染前把所有png图片预先加载到内存里吗？

**Comment by ml-bright** [comment]
可以是可以，但是图片过多的情况下会出现OOM

**Comment by ml-bright** [comment]
合并到 #10
