### ISSUE TITLE
drawText  Bitmap无法释放

### ISSUE THREAD

**Issue by xhly521** [ChillingVan/android-openGL-canvas#92]
在CompareGLView的onGLDraw中调用drawText,通过requestRender多次绘制，android studio 的dump heap 查看内存 有多个bitmap无法释放

**Comment by ChillingVan** [comment]
例子写得不太好，每次draw的时候会重新创建一个bitmap，应该只创建一次就行。然后这个bitmap在CanvasGL里面是用WeakHashMap引用的，被弱引用着。只有内存不足才会去清除。或者释放CanvasGL也会触发清除。
如果需要的话，还可以手动调clearTextureCache来清除
