### ISSUE TITLE
E/GLES20Canvas: GL error: 1285

### ISSUE THREAD

**Issue by kekhong95** [ChillingVan/android-openGL-canvas#99]
When i draw bitmap when video playing in GLView i had out of memory

![image](https://user-images.githubusercontent.com/17746134/120882234-7333b400-c600-11eb-94e3-fbf6683bd4b3.png)

![image](https://user-images.githubusercontent.com/17746134/120882251-98282700-c600-11eb-9618-c54f08b038ba.png)

I thinks it problem of GLView 

Please help me resolve

**Comment by ChillingVan** [comment]
Could you show how many Bitmaps are drawn and show the size of the Bitmap?
And maybe ICanvasGL.clearBitmapCache() helps

**Comment by kekhong95** [comment]
Hi @ChillingVan 
Thanks for answer

I try with recommend clearBitmapCache before draw bitmap . but it not work.

![image](https://user-images.githubusercontent.com/17746134/120884087-14276c80-c60b-11eb-80a2-150b2e2d0993.png)

I need draw bitmap every frame of video 

size of bitmmap : 1166400

Can you help me resolve it ???

**Comment by kekhong95** [comment]
It work only 10-15 fist frame after lib throw GL error: 1285

**Comment by ChillingVan** [comment]
In CanvasGL, it needs to map Bitmap to texture. So the Bitmap should better be same object. If your Bitmap content changes, you can call ICanvasGL.invalidateContent(). And do not create Bitmap continuously. Try to reused the Bitmap object to avoid reallocation.

**Comment by kekhong95** [comment]
I try scale down bitmap with size 1/2 . It work normal. 
I thinks you can improve problem
Thanks for supported.

**Comment by kekhong95** [comment]
![image](https://user-images.githubusercontent.com/17746134/120931170-aff3ce00-c71a-11eb-949c-84e56c7926ab.png)
![image](https://user-images.githubusercontent.com/17746134/120931194-c69a2500-c71a-11eb-9692-6c7245f801a5.png)
Done issue !
